# fly.toml app configuration file generated for cosmic-capture-back on 2023-06-09T06:05:43-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cosmic-capture-back"
primary_region = "atl"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
